"""Create users table

Revision ID: 2afab8f78605
Revises: 9cfb0ef33038
Create Date: 2022-03-03 17:27:17.020335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afab8f78605'
down_revision = '9cfb0ef33038'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=200).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('email', sa.String(length=200).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('password', sa.String(length=500).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
